databases:
  - name: books_DB
    databaseName: books_db_zdgp


    user: books
    region: singapore

services:
  - type: web
    name: books
    env: ruby
    region: singapore
    plan: free
    buildCommand: "npm install & npm run build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: books_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false